# Generated by Django 4.0.4 on 2022-04-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_game_gamer_game_gametype_game_number_of_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='levelupapi.game'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
