# Generated by Django 4.0.4 on 2022-04-18 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_event_date_event_game_event_organizer_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelupapi.gamer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gametype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelupapi.gametype'),
        ),
    ]
